-- CreateTable
CREATE TABLE `Session` (
    `id` VARCHAR(191) NOT NULL,
    `shop` VARCHAR(191) NOT NULL,
    `state` VARCHAR(191) NOT NULL,
    `isOnline` BOOLEAN NOT NULL DEFAULT false,
    `scope` VARCHAR(191) NULL,
    `expires` DATETIME(3) NULL,
    `accessToken` VARCHAR(191) NOT NULL,
    `userId` BIGINT NULL,
    `firstName` VARCHAR(191) NULL,
    `lastName` VARCHAR(191) NULL,
    `email` VARCHAR(191) NULL,
    `accountOwner` BOOLEAN NOT NULL DEFAULT false,
    `locale` VARCHAR(191) NULL,
    `collaborator` BOOLEAN NULL DEFAULT false,
    `emailVerified` BOOLEAN NULL DEFAULT false,
    `refreshToken` VARCHAR(191) NULL,
    `refreshTokenExpires` DATETIME(3) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Announcement` (
    `id` VARCHAR(191) NOT NULL,
    `shop` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `message` VARCHAR(191) NOT NULL,
    `enabled` BOOLEAN NOT NULL DEFAULT true,
    `order` INTEGER NOT NULL DEFAULT 0,
    `displayPages` VARCHAR(191) NOT NULL DEFAULT 'all',
    `customPageUrl` VARCHAR(191) NULL,
    `countries` VARCHAR(191) NOT NULL DEFAULT 'all',
    `linkUrl` VARCHAR(191) NULL,
    `linkText` VARCHAR(191) NULL,
    `startAt` DATETIME(3) NULL,
    `endAt` DATETIME(3) NULL,
    `backgroundColor` VARCHAR(191) NOT NULL DEFAULT '#1a1a1a',
    `textColor` VARCHAR(191) NOT NULL DEFAULT '#ffffff',
    `bgStyle` VARCHAR(191) NOT NULL DEFAULT 'single',
    `bgGradient` VARCHAR(191) NOT NULL DEFAULT '',
    `bgAnimation` VARCHAR(191) NOT NULL DEFAULT 'none',
    `borderRadius` INTEGER NOT NULL DEFAULT 0,
    `borderSize` INTEGER NOT NULL DEFAULT 0,
    `borderColor` VARCHAR(191) NOT NULL DEFAULT '#000000',
    `fontFamily` VARCHAR(191) NOT NULL DEFAULT 'inherit',
    `fontSize` INTEGER NOT NULL DEFAULT 14,
    `fontBold` BOOLEAN NOT NULL DEFAULT false,
    `textAnimation` VARCHAR(191) NOT NULL DEFAULT 'none',
    `customCss` VARCHAR(191) NOT NULL DEFAULT '',
    `rotationMode` VARCHAR(191) NOT NULL DEFAULT 'static',
    `countdownEnabled` BOOLEAN NOT NULL DEFAULT false,
    `countdownEndAt` DATETIME(3) NULL,
    `countdownExpiredMessage` VARCHAR(191) NULL,
    `cartGoalEnabled` BOOLEAN NOT NULL DEFAULT false,
    `cartGoalAmount` DOUBLE NULL,
    `cartGoalMessage` VARCHAR(191) NULL,
    `cartGoalAchievedMessage` VARCHAR(191) NULL,
    `barType` VARCHAR(191) NOT NULL DEFAULT 'simple',
    `slideDuration` INTEGER NOT NULL DEFAULT 5,
    `showCloseButton` BOOLEAN NOT NULL DEFAULT false,
    `position` VARCHAR(191) NOT NULL DEFAULT 'top',
    `sticky` BOOLEAN NOT NULL DEFAULT false,
    `customerTargetingType` VARCHAR(191) NOT NULL DEFAULT 'all',
    `customerTargetingTags` VARCHAR(191) NOT NULL DEFAULT '',
    `customerTargetingSpend` DOUBLE NOT NULL DEFAULT 0.0,
    `slidesJson` VARCHAR(191) NOT NULL DEFAULT '[]',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `Announcement_shop_idx`(`shop`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
